# action.yml
name: 'Execute Ansible Playbook'
author: 'codeg.iq@gmail.com'
description: 'Executes an Ansible Playbook as Github Action'
inputs:
  playbookName:
    description: 'Name of the playbook in your workspace.'
    required: true
  inventoryFile:
    description: 'Name of the inventory file to use.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.playbookName }}
    - ${{ inputs.inventoryFile }}]
branding:
  icon: 'cloud-lightning'
  color: 'blue'