version: "3.9"

services:
  db:
    container_name: postgres_db
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  web:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/myshop
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
  redis:
    image: redis:alpine
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=lilith
      - RABBITMQ_DEFAULT_PASS=Vallakavaddi
volumes:
  db_data: {}
  shop_data: {}