version: "3.9"
#TODO: Change user and password details from defaults
services:
  db:
    container_name: postgres_db
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  pgadmin:
    container_name: pgadmin_conatiner
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin/data
  web:
    build:
      context: .
#    command: ddtrace-run python manage.py runserver 0.0.0.0:8000
    command:
      - django-admin makemessages --all
      - django-admin compilemessages
      - celery -A myshop worker -l info
      - celery -A myshop flower
      - python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/myshop
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/var/lib/redis/data
    expose:
      - "6379"
    ports:
      - "6379:6379"
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3-management
    restart: always
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/data
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
volumes:
  db_data: {}
  pgadmin_data: {}
  redis_data: {}
  rabbitmq_data: {}